services:
  - type: web
    name: casa-vieja
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false